# server configuration
server:
  port: 8000

# spring configuration
spring:
  application:
    name: rest-api-gateway

  cloud:
    gateway:
      routes:
        - id: worker-node
          uri: lb://worker-node
          predicates:
            - Path=/worker-node/**
          filters:
            - RewritePath=/worker-node/(?<segment>.*), /$\{segment}
