# server configuration
server:
  port: 0

spring:
  application:
    name: worker-node

# scheduler configuration
scheduler:
  mode: PARTITIONING

  partitioning:
    max-partitions: 10

  zookeeper:
    connection-properties:
      connect-string: 127.0.0.1:2181

    discovery-properties:
      instance-id: ${spring.application.name}-${random.value}
