apiVersion: v1
kind: Service
metadata:
  labels:
    service: docker-registry
  name: docker-registry
spec:
  type: LoadBalancer
  selector:
    service: docker-registry
  ports:
    - name: client
      port: 5000
      targetPort: 5000

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: docker-registry
  name: docker-registry
spec:
  selector:
    matchLabels:
      service: docker-registry
  template:
    metadata:
      labels:
        service: docker-registry
    spec:
      containers:
        - image: registry:2.8.1
          name: docker-registry
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /var/lib/registry
              name: docker-registry-data
  volumeClaimTemplates:
    - metadata:
        name: docker-registry-data
      spec:
        storageClassName: nfs-csi
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
