apiVersion: v1
kind: Service
metadata:
  labels:
    service: wireguard
  name: wireguard
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.20
  selector:
    service: wireguard
  ports:
    - name: client
      port: 51820
      targetPort: 51820
      protocol: UDP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: wireguard
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      service: wireguard
  template:
    metadata:
      labels:
        service: wireguard
    spec:
      containers:
        - image: linuxserver/wireguard:1.0.20210914
          name: wireguard
          ports:
            - containerPort: 51820
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          env:
            - name: PEERS
              value: "1"
            - name: SERVERURL
              value: "192.168.1.20"
            - name: ALLOWEDIPS
              value: "10.0.0.0/8"
          volumeMounts:
            - mountPath: /config
              name: wireguard-data
  volumeClaimTemplates:
    - metadata:
        name: wireguard-data
      spec:
        storageClassName: nfs-csi
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
