# server configuration
server:
  port: 8000

# spring configuration
spring:
  application:
    name: rest-api-gateway

  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181

    gateway:
      routes:
        - id: worker-node
          uri: lb://worker-node
          predicates:
            - Path=/worker-node/**
          filters:
            - RewritePath=/worker-node/(?<segment>.*), /$\{segment}
