# server configuration
server:
  port: 8000

# spring configuration
spring:
  application:
    name: rest-api-gateway

  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods: '*'
            allowed-headers: '*'

      routes:
        - id: worker-node-partitioning
          uri: lb://worker-node-partitioning
          predicates:
            - Path=/worker-node-partitioning/**
          filters:
            - RewritePath=/worker-node-partitioning/(?<segment>.*), /$\{segment}

        - id: worker-node-leadership
          uri: lb://worker-node-leadership
          predicates:
            - Path=/worker-node-leadership/**
          filters:
            - RewritePath=/worker-node-leadership/(?<segment>.*), /$\{segment}
